name: Build and Release Rust Crate

on:
  push:
    branches:
      - '**' # Triggers on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.72.0' # Specify the Rust version you need
          components: 'clippy, rustfmt' # Optional: Additional components to install

      - name: Install Cargo dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test

      - name: Build crate
        run: cargo build --release
        # Builds the crate in release mode

      - name: Create Tag
        id: create_tag
        run: |
          # Create a version tag based on the current date or commit hash
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: success() # This ensures the release is created only if tests and build succeed
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
