name: Build and Release Rust Crate

on:
  push:
    branches:
      - '**' # Triggers on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.72.0' # Specify the Rust version you need
          components: 'clippy, rustfmt' # Optional: Additional components to install

      - name: Install Cargo dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test

      - name: Build crate
        run: cargo build --release
        # Builds the crate in release mode

      - name: Determine Version and Tag
        id: determine_version
        run: |
          # Extract version from Cargo.toml
          VERSION=$(grep '^version' Cargo.toml | sed -E 's/version\s*=\s*"(.*)"/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          # Check if the tag already exists
          TAG_NAME="v${VERSION}"
          if git rev-parse "${TAG_NAME}" >/dev/null 2>&1; then
            echo "Tag ${TAG_NAME} already exists. Incrementing version..."
            # Find the highest existing tag and increment the patch version
            TAGS=$(git tag -l 'v*')
            TAG_NAME=$(echo "$TAGS" | sort -V | tail -n 1 | awk -F. -v OFS=. '{print $1 "." $2 "." $3+1}')
          fi

          echo "Using tag: ${TAG_NAME}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create and Push Tag
        id: create_tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ env.TAG_NAME }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.TAG_NAME }}
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: success() # This ensures the release is created only if tests and build succeed
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
          tag_name: ${{ env.TAG_NAME }} # Ensure the release action uses the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
